futurismo-org/titan

reactjs/src/components/molecules/Footer.jsx
reactjs/src/components/molecules/challenges/ChallengeBody.jsx
reactjs/src/components/molecules/challenges/ChallengeNavbar.jsx
reactjs/src/components/organisms/Challenge.jsx
reactjs/src/components/organisms/Challenges.jsx

チャレンジ詳細のタブメニュー作成

---

firebase/functions/graphql/data/resolvers.js
firebase/functions/graphql/data/schema.js
package.json
reactjs/.eslintignore
reactjs/.eslintrc.js
reactjs/package.json
reactjs/src/components/atoms/ChallengeCard.jsx
reactjs/src/components/molecules/challenges/ChallengeHeader.jsx
reactjs/src/components/organisms/Challenge.jsx
reactjs/src/components/organisms/Challenges.jsx
reactjs/src/components/organisms/admin/Admin.jsx
reactjs/src/components/organisms/admin/ChallengeForm.jsx
reactjs/src/components/organisms/admin/Challenges.jsx
reactjs/src/components/organisms/admin/DashBoard.jsx
reactjs/yarn.lock
yarn.lock

チャレンジ管理(admin)

---

codegen.yml
firebase/functions/.eslintignore
firebase/functions/.eslintrc.js
firebase/functions/lib/package.json
firebase/functions/package.json
firebase/functions/src/graphql/data/resolvers.ts
firebase/functions/src/graphql/data/schema.ts
firebase/functions/src/graphql/gen/graphql-resolver-types.ts
firebase/functions/src/graphql/server.ts
firebase/functions/src/index.ts
firebase/functions/src/utils/admin.ts
firebase/functions/tsconfig.json
firebase/functions/yarn.lock
graphql/mutations.graphql
graphql/queries.graphql
graphql/schema.graphql
package.json
reactjs/.eslintignore
reactjs/.eslintrc.js
reactjs/src/components/organisms/Challenge.tsx
reactjs/src/components/organisms/Challenges.tsx
reactjs/src/gen/graphql-client-api.tsx
reactjs/tsconfig.json
yarn.lock

graphql-codegen導入

---

firebase/functions/bin/db_clear.sh
firebase/functions/bin/db_seeds.sh
firebase/functions/package.json
firebase/functions/src/cli/seeds.ts
firebase/functions/yarn.lock

seedスクリプトの追加

---

firebase/functions/bin/db_clear.sh
firebase/functions/bin/db_seeds.sh
firebase/functions/src/cli/seeds.ts

カテゴリとチャレンジ見直し

---

package.json
reactjs/src/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/components/molecules/challenges/ChallengeOverview.tsx
reactjs/src/components/molecules/challenges/ChallengeRules.tsx
reactjs/src/components/organisms/Challenge.tsx
reactjs/src/components/organisms/admin/ChallengeForm.tsx
yarn.lock

管理画面の入力フォーム

---

firebase/functions/package.json
firebase/functions/src/cli/seeds.ts
firebase/functions/src/user.ts
firebase/functions/src/utils/admin.ts
reactjs/package.json
reactjs/src/actions/userAction.ts
reactjs/src/components/atoms/AuthButton.tsx
reactjs/src/components/atoms/AuthModal.tsx
reactjs/src/components/atoms/JoinButton.tsx
reactjs/src/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/components/molecules/challenges/ChallengeLeaderBoard.tsx
reactjs/src/constants/actionTypes.ts
reactjs/src/containers/ChallengeLeaderBoardContainer.ts
reactjs/src/containers/userContainer.ts
reactjs/src/reducers/index.ts
reactjs/src/reducers/reducuerUtil.ts
reactjs/src/reducers/userReducer.ts
reactjs/yarn.lock

リーダーボードにに最終の活動日を表示#127

---

firebase/functions/package.json
firebase/functions/src/cli/seeds.ts
reactjs/package.json
reactjs/src/components/atoms/AdminRoute.tsx
reactjs/src/components/atoms/AuthModal.tsx
reactjs/src/components/organisms/App.tsx

認証ルーティング設定 #83

---

reactjs/src/components/atoms/AuthButton.tsx
reactjs/src/components/atoms/JoinButton.tsx
reactjs/src/components/atoms/UserItem.tsx
reactjs/src/components/molecules/DashBoardPaper.tsx
reactjs/src/components/molecules/NavToolbar.tsx
reactjs/src/components/molecules/TopToolbar.tsx
reactjs/src/components/molecules/challenges/ChallengeLeaderBoard.tsx
reactjs/src/components/molecules/challenges/ChallengePostRecord.tsx
reactjs/src/components/templates/DefaultLayout.tsx
reactjs/src/lib/theme.ts

モバイルデザイン対応

---

firebase/functions/src/cli/seeds.ts
firebase/functions/src/index.ts
reactjs/src/components/atoms/AuthModal.tsx
reactjs/src/components/molecules/TopToolbar.tsx
reactjs/src/components/organisms/Category.tsx

userモデルの作成方法の変更

---

reactjs/src/components/atoms/CircularProgress.tsx
reactjs/src/components/molecules/challenges/ChallengeLeaderBoard.tsx
reactjs/src/components/molecules/challenges/ChallengePosts.tsx
reactjs/src/components/organisms/Categories.tsx
reactjs/src/components/organisms/Category.tsx
reactjs/src/components/organisms/Challenge.tsx
reactjs/src/components/organisms/Challenges.tsx
reactjs/src/components/organisms/DashBoard.tsx
reactjs/src/components/organisms/admin/Challenges.tsx

loadingの改善

---

firebase/functions/bin/db_clear.sh
firebase/functions/bin/db_seeds.sh
firebase/functions/lib/package.json
firebase/functions/src/cli/seeds.ts
firebase/functions/src/utils/admin.ts
reactjs/public/index.html
reactjs/src/components/atoms/ChallengeCard.tsx
reactjs/src/components/organisms/DashBoard.tsx

プライベートチャレンジ機能

---

firebase/functions/src/cli/seeds.ts
reactjs/src/components/atoms/ChallengeCategoryLink.tsx
reactjs/src/components/atoms/JoinButton.tsx
reactjs/src/components/molecules/challenges/ChallengeHeader.tsx

チャレンジからカテゴリへのリンク

---

landing-page/index.html

ランディングページのSEO

---

landing-page/index.html

LINE@登録ボタンを設置

---

reactjs/src/components/molecules/challenges/ChallengePosts.tsx

スコア記録のロジック追加

---

.circleci/config.yml

CircleCI導入 #161

---

.circleci/config.yml
README.md
reactjs/package.json
reactjs/src/components/molecules/challenges/ChallengeOverview.tsx
reactjs/src/components/molecules/challenges/ChallengeRules.tsx
reactjs/src/components/organisms/admin/CategoryForm.tsx
reactjs/src/components/organisms/admin/ChallengeForm.tsx
reactjs/yarn.lock

Markdownエディタ組み込み

---

firebase/functions/src/handlers/stripe.ts
firebase/functions/src/index.ts
reactjs/src/components/atoms/CheckoutForm.tsx
reactjs/src/components/organisms/admin/ChallengeForm.tsx

stripe coupon#204

---

reactjs/package.json
reactjs/src/components/atoms/ChallengeButton.tsx
reactjs/src/components/atoms/ChallengeCard.tsx
reactjs/src/components/atoms/ChallengeCategoryLink.tsx
reactjs/src/components/molecules/categories/CategoryHeader.tsx
reactjs/src/components/molecules/challenges/ChallengeHeader.tsx
reactjs/src/components/molecules/challenges/ChallengeNavbar.tsx
reactjs/yarn.lock

mobile-ux#157

---

reactjs/src/components/molecules/challenges/ChallengeHeader.tsx

大会終了後のボタン操作

---

reactjs/src/components/molecules/DashBoardPaper.tsx
reactjs/src/components/molecules/challenges/ChallengeStatistics.tsx
reactjs/src/components/organisms/Challenges.tsx

大会終了時のみせかた

---

reactjs/src/components/organisms/admin/ChallengeForm.tsx

feature#284

---

reactjs/src/components/molecules/challenges/ChallengePostController.tsx

reset-after#304

---

firebase/functions/src/cli/seeds.ts
reactjs/src/components/atoms/challenges/ChallengeCard.tsx
reactjs/src/components/organisms/admin/Categories.tsx
reactjs/src/components/organisms/admin/ChallengeForm.tsx
reactjs/src/components/organisms/admin/Challenges.tsx
reactjs/src/components/organisms/admin/DashBoard.tsx
reactjs/src/lib/moment.ts

管理画面ダッシュボードの改善

---

reactjs/src/components/atoms/TwitterButton.tsx

Twitterシェア

---

reactjs/src/actions/ogpAction.ts
reactjs/src/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/components/molecules/challenges/ChallengeUserDashBoard.tsx
reactjs/src/components/organisms/App.tsx
reactjs/src/components/templates/Head.tsx
reactjs/src/constants/actionTypes.ts
reactjs/src/constants/appInfo.ts
reactjs/src/containers/ChallengeLeaderBoardContainer.ts
reactjs/src/containers/challengeUserDashboardContainer.ts
reactjs/src/index.tsx
reactjs/src/reducers/index.ts
reactjs/src/reducers/ogpReducer.ts

Twitterシェア時にタイトルを設置

---

firebase/functions/src/cli/seeds.ts
reactjs/src/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/components/molecules/challenges/ChallengeOverview.tsx
reactjs/src/components/organisms/admin/ChallengeForm.tsx

embed-movie#324

---

reactjs/src/components/atoms/YoutubeWidget.tsx
reactjs/src/components/atoms/challenges/ChallengeSchedule.tsx
reactjs/src/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/components/molecules/challenges/ChallengeHeader.tsx
reactjs/src/components/molecules/challenges/ChallengeOverview.tsx

チャレンジスケジュール

---

reactjs/src/components/atoms/CheckoutForm.tsx

大会参加でチャンネルに通知

---

reactjs/package.json
reactjs/src/components/molecules/TopicForm.tsx
reactjs/src/components/molecules/challenges/ChallengePostController.tsx
reactjs/src/components/organisms/App.tsx
reactjs/src/lib/resourceUtil.ts
reactjs/src/lib/urlUtil.ts
reactjs/src/reducers/index.ts
reactjs/src/store.ts
reactjs/yarn.lock

１日に複数回投稿できるバグ

---

reactjs/src/components/atoms/AuthModal.tsx

メールアドレスでのログインでユーザ作成ができない

---

firebase/functions/src/cli/seeds.ts
reactjs/src/components/atoms/AuthModal.tsx
reactjs/src/components/atoms/UserAvatar.tsx
reactjs/src/components/atoms/UserItem.tsx
reactjs/src/components/molecules/challenges/ChallengeLeaderBoard.tsx
reactjs/src/components/organisms/Ranking.tsx
reactjs/src/lib/urlUtil.ts

TwtiterURLの修正

---

reactjs/src/components/organisms/Ranking.tsx

ランキング表示の改善

---

firebase/functions/src/handlers/ogp.ts
firebase/functions/src/index.ts

チャレンジページのOGP

---

reactjs/src/actions/challengeAction.ts
reactjs/src/connects/ChallengesConnect.tsx
reactjs/src/native/components/organisms/Challenges.tsx
reactjs/src/native/components/organisms/Home.tsx
reactjs/src/native/containers/ChallengesContainer.tsx
reactjs/src/native/containers/ChallengesContainers.tsx
reactjs/src/native/containers/DashBoardContainer.tsx
reactjs/src/web/components/organisms/Challenges.tsx
reactjs/src/web/components/organisms/Home.tsx
reactjs/src/web/containers/ChallengesContainers.tsx

Expo - Challenge一覧

---

firebase/functions/src/cli/seeds.ts
reactjs/package.json
reactjs/src/@types/react-native-simple-radio-button.d.ts
reactjs/src/connects/ChallengeConnect.tsx
reactjs/src/connects/ChallengeUserDashBoardConnect.tsx
reactjs/src/connects/ChallengeUserSettingsConnect.tsx
reactjs/src/lib/challenge.ts
reactjs/src/lib/moment.ts
reactjs/src/native/components/atoms/Toast.tsx
reactjs/src/native/components/atoms/TwitterButton.tsx
reactjs/src/native/components/atoms/challenges/ChallengeNumberWidget.tsx
reactjs/src/native/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/native/components/molecules/challenges/ChallengeChart.tsx
reactjs/src/native/components/molecules/challenges/ChallengeGrass.tsx
reactjs/src/native/components/molecules/challenges/ChallengeHistories.tsx
reactjs/src/native/components/molecules/challenges/ChallengePostRecord.tsx
reactjs/src/native/components/molecules/challenges/ChallengeStatistics.tsx
reactjs/src/native/components/molecules/challenges/ChallengeUserDashBoard.tsx
reactjs/src/native/components/molecules/challenges/ChallengeUserSettings.tsx
reactjs/src/native/components/organisms/Challenge.tsx
reactjs/src/native/containers/ChallengeUserDashBoardContainer.tsx
reactjs/src/native/containers/ChallengeUserSettingsContainer.tsx
reactjs/src/web/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/web/components/molecules/challenges/ChallengeGrass.tsx
reactjs/src/web/components/molecules/challenges/ChallengeHistories.tsx
reactjs/src/web/components/molecules/challenges/ChallengeStatistics.tsx
reactjs/src/web/components/molecules/challenges/ChallengeUserDashBoard.tsx
reactjs/src/web/components/molecules/challenges/ChallengeUserSettings.tsx
reactjs/src/web/containers/ChallengeUserSettingsContainer.tsx
reactjs/yarn.lock

Expo - Challenge

---

reactjs/app.json
reactjs/src/native/components/molecules/TopicForm.tsx
reactjs/src/native/components/templates/DefaultLayout.tsx

(Andoird)TopicFormでKeyboardが隠れる

---

reactjs/src/connects/CollectionCardConnect.tsx
reactjs/src/lib/native.ts
reactjs/src/native/components/atoms/CollectionCard.tsx
reactjs/src/native/components/molecules/categories/CategoryChallenge.tsx
reactjs/src/native/components/organisms/Categories.tsx
reactjs/src/native/components/organisms/Challenges.tsx
reactjs/src/native/components/organisms/DashBoard.tsx
reactjs/src/native/components/organisms/Info.tsx
reactjs/src/native/components/organisms/Settings.tsx
reactjs/src/native/containers/CollectionCardContainer.tsx
reactjs/src/web/components/organisms/admin/CategoryForm.tsx
reactjs/src/web/components/organisms/admin/ChallengeForm.tsx

Appleセンシティブ対応

---

reactjs/package.json
reactjs/src/@types/react-native-image-overlay.d.ts
reactjs/src/connects/NavDrawerConnect.tsx
reactjs/src/native/components/molecules/NavDrawer.tsx
reactjs/src/native/components/templates/DefaultLayout.tsx
reactjs/src/native/containers/NavDrawer.tsx
reactjs/yarn.lock

Drawerのオーバレイ

---

reactjs/src/connects/SettingsConnect.tsx
reactjs/src/lib/firebase.ts
reactjs/src/native/components/organisms/App.tsx
reactjs/src/native/components/organisms/Settings.tsx
reactjs/src/web/components/organisms/Settings.tsx

アイコンアップロード

---

reactjs/package.json
reactjs/src/native/components/atoms/CollectionCard.tsx
reactjs/src/native/components/atoms/Title.tsx
reactjs/yarn.lock

Typography改善

---

reactjs/src/native/components/atoms/challenges/ChallengeButton.tsx
reactjs/src/native/components/molecules/challenges/ChallengePostController.tsx

Discord Mobile対応

---

reactjs/src/connects/ChallengeLeaderBoardConnect.tsx
reactjs/src/lib/theme.ts
reactjs/src/native/components/molecules/challenges/ChallengeLeaderBoard.tsx
reactjs/src/web/components/molecules/challenges/ChallengeLeaderBoard.tsx

リーダボードUX改善

---

reactjs/package.json
reactjs/src/actions/giphyAction.ts
reactjs/src/connects/ChallengeButtonConnect.tsx
reactjs/src/constants/actionTypes.ts
reactjs/src/lib/general.ts
reactjs/src/lib/giphy.ts
reactjs/src/native/components/atoms/challenges/ChallengeButton.tsx
reactjs/src/native/components/molecules/challenges/ChallengePostController.tsx
reactjs/src/native/components/organisms/App.tsx
reactjs/src/native/components/organisms/Challenge.tsx
reactjs/src/native/components/organisms/DashBoard.tsx
reactjs/src/native/components/organisms/Giphy.tsx
reactjs/src/native/components/templates/DefaultLayout.tsx
reactjs/src/reducers/gitphyReducer.ts
reactjs/src/reducers/index.ts
reactjs/yarn.lock

Giphyを表示する

---

reactjs/src/lib/native.ts
reactjs/src/native/components/atoms/CollectionCard.tsx
reactjs/src/native/components/atoms/MoreLink.tsx
reactjs/src/native/components/atoms/Title.tsx
reactjs/src/native/components/atoms/TouchableText.tsx
reactjs/src/native/components/atoms/challenges/ChallengeButton.tsx
reactjs/src/native/components/atoms/challenges/ChallengeCategoryBadge.tsx
reactjs/src/native/components/molecules/Header.tsx
reactjs/src/native/components/molecules/NavDrawer.tsx
reactjs/src/native/components/molecules/Topic.tsx
reactjs/src/native/components/molecules/TopicList.tsx
reactjs/src/native/components/molecules/Topics.tsx
reactjs/src/native/components/molecules/categories/CategoryDashBoard.tsx
reactjs/src/native/components/molecules/categories/CategoryHeader.tsx
reactjs/src/native/components/molecules/challenges/ChallengeHeader.tsx
reactjs/src/native/components/molecules/challenges/ChallengeLeaderBoard.tsx
reactjs/src/native/components/molecules/challenges/ChallengePostController.tsx
reactjs/src/native/components/organisms/App.tsx
reactjs/src/native/components/organisms/Categories.tsx
reactjs/src/native/components/organisms/Category.tsx
reactjs/src/native/components/organisms/Challenges.tsx
reactjs/src/native/components/organisms/DashBoard.tsx
reactjs/src/native/components/templates/DefaultLayout.tsx
reactjs/yarn.lock

Appleストアアプリ申請対応（主にデザイン)

---

reactjs/src/native/components/atoms/YoutubeWidget.tsx
reactjs/src/native/components/molecules/challenges/ChallengeOverview.tsx
reactjs/yarn.lock

Expo Video Player試す

---

reactjs/package.json
reactjs/src/lib/firebase.ts
reactjs/src/lib/native.ts
reactjs/src/native/components/atoms/AuthScreen.tsx
reactjs/src/web/components/atoms/AuthModal.tsx
reactjs/yarn.lock

アイコンのアップロード(サインアップ)

---

reactjs/bin/update-build-timestamp.sh
reactjs/package.json
reactjs/src/index.native.tsx
reactjs/src/index.tsx
reactjs/src/native/ReactotronConfig.ts
reactjs/src/native/components/organisms/Info.tsx
reactjs/src/native/store.ts
reactjs/src/web/ReactotronConfig.ts
reactjs/src/web/components/organisms/Info.tsx
reactjs/yarn.lock

Build Commit log

---

reactjs/src/connects/ContactFormConnect.tsx
reactjs/src/native/components/molecules/ContactForm.tsx
reactjs/src/native/components/organisms/Contact.tsx
reactjs/src/native/components/organisms/Home.tsx
reactjs/src/native/components/organisms/Info.tsx
reactjs/src/native/containers/ContactFormContainer.tsx
reactjs/src/web/components/molecules/ContactForm.tsx
reactjs/src/web/components/organisms/Contact.tsx
reactjs/src/web/components/organisms/Home.tsx
reactjs/src/web/components/organisms/Info.tsx
reactjs/src/web/containers/ContactFormContainer.tsx

お問い合わせフォームの作成

---

reactjs/src/native/components/molecules/challenges/ChallengePostController.tsx
reactjs/src/web/components/molecules/challenges/ChallengePostController.tsx

計算アルゴリズムの変更

---

firebase/functions/src/cli/seeds.ts
reactjs/src/connects/SettingsConnect.tsx
reactjs/src/lib/moment.ts
reactjs/src/lib/theme.ts
reactjs/src/native/components/molecules/NavDrawer.tsx
reactjs/src/web/components/atoms/UserAvatar.tsx
reactjs/src/web/components/molecules/NavDrawer.tsx
reactjs/src/web/components/molecules/categories/CategoryHeader.tsx
reactjs/src/web/components/molecules/challenges/ChallengeHeader.tsx
reactjs/src/web/components/organisms/Profile.tsx
reactjs/src/web/components/organisms/Settings.tsx

User profile header#web

---

reactjs/src/native/components/organisms/Users.tsx

Users#mobile

---

reactjs/src/connects/ProfileBodyConnect.tsx
reactjs/src/connects/TotalScoreBoardConnect.tsx
reactjs/src/lib/meigen.ts
reactjs/src/native/components/atoms/BlockButton.tsx
reactjs/src/native/components/atoms/MuteButton.tsx
reactjs/src/native/components/atoms/TotalScoreBoard.tsx
reactjs/src/native/components/molecules/ProfileBody.tsx
reactjs/src/native/components/molecules/ProfileCategories.tsx
reactjs/src/native/components/molecules/ProfileChallenges.tsx
reactjs/src/native/components/molecules/ProfileHeader.tsx
reactjs/src/native/components/molecules/challenges/ChallengeChart.tsx
reactjs/src/native/components/molecules/challenges/ChallengeHistories.tsx
reactjs/src/native/components/organisms/App.tsx
reactjs/src/native/components/organisms/Hero.tsx
reactjs/src/native/components/organisms/Home.tsx
reactjs/src/native/components/organisms/Profile.tsx
reactjs/src/native/containers/ProfileBodyContainer.tsx
reactjs/src/native/containers/TotalScoreBoardContainer.tsx
reactjs/src/web/components/molecules/ProfileBody.tsx
reactjs/src/web/components/molecules/ProfileChallenges.tsx

#580 
https://www.bootdey.com/react-native-snippet/23/Profile-ui-example

User profile design mobile

---

reactjs/src/connects/ProfileConnect.tsx
reactjs/src/connects/TopicConnect.tsx
reactjs/src/native/components/molecules/Topic.tsx
reactjs/src/native/components/organisms/Profile.tsx
reactjs/src/web/components/organisms/Profile.tsx

blocking-bug#617

---

reactjs/src/native/native-base-theme/variables/material.ts
reactjs/src/web/components/atoms/TextField.tsx
reactjs/src/web/components/molecules/ContactForm.tsx
reactjs/src/web/components/molecules/TopicForm.tsx
reactjs/src/web/components/molecules/challenges/ChallengeUserSettings.tsx
reactjs/src/web/components/organisms/Settings.tsx
reactjs/src/web/components/organisms/admin/CategoryForm.tsx
reactjs/src/web/components/organisms/admin/ChallengeForm.tsx
reactjs/src/web/components/organisms/admin/DocumentForm.tsx

form-outline#614

---

firebase/functions/src/cli/seeds.ts
reactjs/package.json
reactjs/src/@types/react-stack-grid.d.ts
reactjs/src/actions/userAction.ts
reactjs/src/connects/ChallengeGoalsConnect.tsx
reactjs/src/connects/ChallengeJournalConnect.tsx
reactjs/src/native/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/native/components/molecules/challenges/ChallengeGoals.tsx
reactjs/src/native/components/molecules/challenges/ChallengeJournal.tsx
reactjs/src/native/components/molecules/challenges/ChallengeNavbar.tsx
reactjs/src/native/containers/ChallengeGoalsContainer.tsx
reactjs/src/native/containers/ChallengeJournalContainer.tsx
reactjs/src/web/components/atoms/challenges/ChallengeGoalCard.tsx
reactjs/src/web/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/web/components/molecules/challenges/ChallengeGoals.tsx
reactjs/src/web/components/molecules/challenges/ChallengeJournal.tsx
reactjs/src/web/components/molecules/challenges/ChallengeLeaderBoard.tsx
reactjs/src/web/components/molecules/challenges/ChallengeNavbar.tsx
reactjs/src/web/containers/ChallengeGoalsContainer.tsx
reactjs/src/web/containers/ChallengeJournalContainer.tsx
reactjs/yarn.lock

目標シェア機能(web)

---

firebase/functions/src/cli/seeds.ts
reactjs/src/actions/actionUtil.ts
reactjs/src/actions/noteAction.ts
reactjs/src/actions/topicAction.ts
reactjs/src/connects/ChallengeGoalConnect.tsx
reactjs/src/connects/ChallengeObjectiveConnect.tsx
reactjs/src/connects/ChallengeTimelineConnect.tsx
reactjs/src/connects/FlagFormConnect.tsx
reactjs/src/lib/moment.ts
reactjs/src/lib/theme.ts
reactjs/src/web/components/atoms/Flag.tsx
reactjs/src/web/components/atoms/FlagForm.tsx
reactjs/src/web/components/atoms/challenges/ChallengeNote.tsx
reactjs/src/web/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/web/components/molecules/challenges/ChallengeGoal.tsx
reactjs/src/web/components/molecules/challenges/ChallengeNotes.tsx
reactjs/src/web/components/molecules/challenges/ChallengeTimeline.tsx
reactjs/src/web/components/molecules/challenges/ChallengeTimelineItem.tsx
reactjs/src/web/components/molecules/profiles/ProfileHeader.tsx
reactjs/src/web/containers/ChallengeTimelineContainer.tsx

チャレンジタイムライン

---

reactjs/src/connects/DashBoardConnect.tsx
reactjs/src/lib/challenge.ts
reactjs/src/native/components/molecules/categories/CategoryChallenge.tsx
reactjs/src/native/components/molecules/categories/CategoryDashBoard.tsx
reactjs/src/native/components/molecules/challenges/ChallengeBody.tsx
reactjs/src/native/components/molecules/profiles/ProfileBody.tsx
reactjs/src/native/components/organisms/Categories.tsx
reactjs/src/native/components/organisms/Challenges.tsx
reactjs/src/native/components/organisms/DashBoard.tsx
reactjs/src/native/lib/native.ts
reactjs/src/web/components/organisms/DashBoard.tsx
reactjs/src/web/components/organisms/admin/CategoryForm.tsx
reactjs/src/web/components/organisms/admin/ChallengeForm.tsx

Appleレビュー対応(9回目)

---

reactjs/src/connects/QuickActionListConnect.tsx
reactjs/src/native/components/molecules/QuickActionList.tsx

深夜のapple審査がおわったらマージする。それまではなにもしない。

QuickActionの修正

---

reactjs/src/lib/profile.ts

リセット時のProfile

---

reactjs/src/lib/config.ts
reactjs/src/native/components/organisms/App.tsx
reactjs/src/native/lib/native.ts

Apple Review対応

---

reactjs/package.json
reactjs/src/connects/AuthConnect.tsx
reactjs/src/native/components/atoms/Auth.tsx
reactjs/yarn.lock

#727 
以下を参考にして、react-native-simple-twitterのライブラリをv3にUpgradeする。
https://github.com/watanabeyu/react-native-simple-twitter/blob/master/example/src/screens/LoginScreen.tsx
眠いので朝起きてから対応する。

fix-native-twitter-login-failed#727
